# Generated by Django 3.2 on 2023-04-13 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=256)),
                (
                    'year',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=2023,
                            ),
                        ],
                    ),
                ),
                ('description', models.TextField(null=True)),
                (
                    'categorie',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='titles',
                        to='compositions.category',
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='titles',
                        to='compositions.genre',
                    ),
                ),
            ],
        ),
    ]
