# Generated by Django 3.2 on 2023-04-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='genre_to_title',
                to='compositions.genre',
            ),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='title_to_genre',
                to='compositions.title',
            ),
        ),
    ]
