# Generated by Django 3.2 on 2023-04-13 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('compositions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='categorie',
            new_name='category',
        ),
    ]
