# Generated by Django 3.2 on 2023-04-18 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('compositions', '0002_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
