# Generated by Django 3.2 on 2023-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('compositions', '0002_rename_categorie_title_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(
                related_name='titles',
                to='compositions.Genre',
            ),
        ),
    ]
