# Generated by Django 3.2 on 2023-04-20 08:01

import django.db.models.deletion
from django.db import migrations, models

import compositions.validators


class Migration(migrations.Migration):
    dependencies = [
        ('compositions', '0003_remove_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ['name'],
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={
                'ordering': ['name'],
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='genretitle',
            options={
                'verbose_name': 'Жанр произведения',
                'verbose_name_plural': 'Жанры произведения',
            },
        ),
        migrations.AlterModelOptions(
            name='title',
            options={
                'default_related_name': 'titles',
                'ordering': ['id'],
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='genre',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='compositions.genre',
                verbose_name='Жанр',
            ),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='compositions.title',
                verbose_name='Произведение',
            ),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='titles',
                to='compositions.category',
                verbose_name='Категория',
            ),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='Описание'
            ),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(
                related_name='titles',
                through='compositions.GenreTitle',
                to='compositions.Genre',
                verbose_name='Жанр',
            ),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(
                validators=[compositions.validators.validate_year],
                verbose_name='Год создания',
            ),
        ),
    ]
