# Generated by Django 3.2 on 2023-04-18 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0004_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Reviews'},
        ),
    ]
